### ISSUE TITLE
can't get cookie's params

### ISSUE THREAD

**Issue by suhanyujie** [bixuehujin/blink#15]
hello~
I have a problem about get cookie in controller.
When I use the object Request "getCookies" method ,cannot get a cookie in the Request.
thank u.

**Comment by bixuehujin** [comment]
Hi,

The `getCookies()` method returns a `CookieBag` object, you can try the following code:

```
$request->cookies->get('name'); // get cookie by name
$request->cookies->all(); // return all cookies as array
```

**Comment by suhanyujie** [comment]
oh..
The first line of code is available, but “all ()” method, will go wrong...
like this：
`{
name: "blink\core\UnknownMethodException",
message: "Calling unknown method: blink\http\CookieBag::all()",
code: 0,
file: "/www/cms/suhy/blink/vendor/blink/blink/src/core/ObjectTrait.php",
line: 73,
trace: [
"#0 /www/cms/suhy/blink/src/http/controllers/IndexController.php(24): blink\core\Object->__call('all', Array)",
"#1 /www/cms/suhy/blink/src/http/controllers/IndexController.php(24): blink\http\CookieBag->all()",
"#2 [internal function]: app\http\controllers\IndexController->guessYouLike(Object(blink\http\Request))",`

**Comment by bixuehujin** [comment]
uh...

Sorry, there is no `all()` method in `CookieBag`  class, i forgot that~
