### ISSUE TITLE
Swoole Features

### ISSUE THREAD

**Issue by CMCDragonkai** [bixuehujin/blink#24]
I understand that this an HTTP framework built on top of Swoole. But Swoole has many other features, such as allowing one to program websocket servers, tcp servers and making use of asynchronous IO for accessing databases. I just went through the docs, and it doesn't mention any of this. To what extent is Blink meant to support these other swoole features?

**Comment by bixuehujin** [comment]
Hi, 

It is possible to introduce some Swoole features by subclass SwServer, but it may not work well with all Swoole features as Blink is not compatible with asynchronous programing model for now.
