### ISSUE TITLE
关于安装

### ISSUE THREAD

**Issue by suhanyujie** [bixuehujin/blink#27]
hello~
  你好，今天想使用一下您的开源项目blink,但在安装使用时，发现了几个小问题：

 我使用您readme中提供的唯一安装方法`composer create-project --prefer-dist blink/seed your-app`,可能是因为国内的原因吧，没法安装。
 于是我尝试git clone，但clone的结果和文档说的目录结构不太一样，没有找到router.php文件。
 是否有一些其他的安装方法呢？
 谢谢~

**Comment by bixuehujin** [comment]
你好，

目前文档有一些滞后，master 里的一些新特性并没有同步到文档，所以和 readme 中的目录结构不一致。

如果国内使用 composer 有问题，可以尝试使用国内的镜像安转试试：http://www.phpcomposer.com/

**Comment by suhanyujie** [comment]
好的，谢谢
