### ISSUE TITLE
我看了Blink的生命周期，希望得到更详细的讲解

### ISSUE THREAD

**Issue by pavlelee** [bixuehujin/blink#3]
我看到大致意思是先在主进程创建app实例，然后复制成多个子进程，这个时候只是简单的app实例在进程中，那么进程之间的产生的服务是怎么共享的？？

**Comment by bixuehujin** [comment]
在服务其启动的时候会创建多个子进程（worker），实际处理请求的都是这些子进程，每个子进程都有一个app实例，他们之间时相互独立的。如果要在app实例之间共享数据，用Redis，MySQL 之类的外部存储就行了。
