### ISSUE TITLE
[Enhancement]建议

### ISSUE THREAD

**Issue by slince** [bixuehujin/blink#35]
-  Http library添加支持PSR7 
PSR7已经是相当成熟的规范了，现在已经大规模的被框架适用

- 添加数据库访问层
如果作者不想自己实现的话，doctrine是个不错的方案；在核心层做个桥接以方便使用

- 命名空间格式大小写混合的写法是参照thinkphp的吧，着实辣眼睛,建议换成pascal命名法
比较主流框架都是这个，用户迁移过来也不易反感

**Comment by bixuehujin** [comment]
感谢建议~

1、PSR7 已经在考虑了，#14 是目前的一个实现，但因为 PSR7 Immutable 的设计，和 Blink 有一些冲突，目前还没有想到更优雅的解决方案，所以还没有 merge 到主干。

2、Blink 核心没有添加数据库组件的打算，不过可以很方便的基于已有的库比如 doctrine 封装一个，目前其实有一个对 laravel database 的简单封装 https://github.com/bixuehujin/blink-laravel-database ，但没有公开放出来。

3、没有注意到 thinkphp 也使用的小写命名空间，不知道它的原因是什么。Blink 当初采用小写，一方面是借鉴 Yii，另一方面 Blink 更提倡使用单个单词作为命名空间，让命名空间的层级更扁平简洁。针对 Yii，也有一个相应的讨论 http://www.yiiframework.com/forum/index.php/topic/41622-namespaces-naming-convention/
