### ISSUE TITLE
这个框架怎么创建WEBSOCKET

### ISSUE THREAD

**Issue by ehvu** [bixuehujin/blink#37]
这个框架怎么创建WEBSOCKET

**Comment by bixuehujin** [comment]
Blink 没有直接的 WebSocket 支持，如果要在 Blink 中使用 WebSocket，目前可以通过继承  `blink\server\SwServer` 并重写 `createServer()` ，然后在 `src/config/server.php` 中进行配置:

```
    'class' => '\path\to\your\CustomServer',
```
