### ISSUE TITLE
php7.2.0 Fatal error: Cannot use blink\core\Object as Object because 'Object' is a special class name

### ISSUE THREAD

**Issue by nbzx** [bixuehujin/blink#46]
in vendor/blink/blink/src/server/Server.php on line 5

-------------
PHP 7.2.0 (cli) (built: Dec  3 2017 21:47:51) ( NTS )
Copyright (c) 1997-2017 The PHP Group
Zend Engine v3.2.0, Copyright (c) 1998-2017 Zend Technologies
    with Xdebug v2.6.0alpha1, Copyright (c) 2002-2017, by Derick Rethans

**Comment by bixuehujin** [comment]
This is already fixed in https://github.com/bixuehujin/blink/commit/191c6f0d62c88b0a4a19c68a658254acc24023c3 

You can change the version to `dev-master` in composer.json
