### ISSUE TITLE
运行php blink server:server报了下面这个错

### ISSUE THREAD

**Issue by huangcong12** [bixuehujin/blink#47]
PHP Fatal error:  Cannot use blink\core\Object as Object because 'Object' is a special class name in /data/wwwroot/www.hcode.wang/vendor/blink/blink/src/server/Server.php on line 5

环境：PHP 7.2.1、swoole2.几忘了

**Comment by bixuehujin** [comment]
duplicated to https://github.com/bixuehujin/blink/issues/46
