### ISSUE TITLE
Incorrect assumptions in readme.md

### ISSUE THREAD

**Issue by nogrp** [bixuehujin/blink#5]
I noticed that your readme states the following:

> In php-fpm or mod_php, all resources like objects and database connections only live within a single request

This isn't true for `php-fpm`, it's actually the exact opposite. Database connections **specifically** persist. Objects don't, but the lexing and all the heavy work is done and stored to OPCache. I was referred to this repository by a potential client, and it seems that you've got a mistake there that leads people to wrong conclusions.

The other thing I've noticed is the claim that you're 100% faster. I couldn't find the actual proof of the statement for comparison, but from a lot of testing I've conducted with similar projects - the best you can hope for is to be _near_ performance of `php-fpm`, there is no possibility to achieve more since essentially a `cli` executed script is nearly the same as `php-fpm` executed one from the execution POV. 

I don't want to be "that guy" who dumps on someone's project, I think you have an interesting tool here but I believe you would agree with me that incorrect assumptions are quickly to propagate as "facts" when in reality - it's not true. 

I wish you all the best, hopefully you won't take my comment/issue the wrong way, the intent is not to belittle your work.

**Comment by bixuehujin** [comment]
> This isn't true for php-fpm, it's actually the exact opposite. Database connections specifically persist. 

AFAIK, Database connections is not persistant by default, but indeed there is a way to make connections persistant,  such as the `PDO::ATTR_PERSISTENT` attribute for PDO. I think i should update the README to reflect this.

> but the lexing and all the heavy work is done and stored to OPCache.

OPCache cache is not everything, OPCache is just a series of opcode, the opcodes still need to be executed by the vm and form the objects that we used in userland. The execution process of opcodes still take much of the time.

> The other thing I've noticed is the claim that you're 100% faster. I couldn't find the actual proof of the statement for comparison

In simple application like 'hello world', the performance is actually more than 100%. In real world application, the performance improvements depends on related business logic, i can not give you the exactly results for now.

Besides, i am still working on a CgiServer to make Blink running upon php-fpm, and then we can have more detailed and precised benchmark comparison.

Anyway, thanks for your suggestion.

Regards

**Comment by nogrp** [comment]
Thank you for the response. I've tried a few different stacks similar to yours (which use a php extension and `cli` php to run the script) and every single time the reason why `php-fpm` was seemingly slower was due to incorrect benchmarking. For example, `php-fpm` will keep objects in memory for a number of requests before the child process is killed and restarted. That means a long-running CLI app does exactly the same thing. You are correct, opcache isn't a magic hammer and objects need to be re-created from cached opcodes. This happens less-frequently with fpm and behavior is controllable. 

Also, the stacks I ran always benchmarked the http server and fpm on a single machine versus a cli script on a single machine - as you can tell, that's quite unfair. I'm not into speed as much as I'm into reliability so I don't want to touch upon the subject of performance (I'm 100% sure your stack is quite fast, probably a few dozens of times faster than `mod_php`). Anyway, once again, thanks for the fast response, I wish you good luck with the project and I starred it - hopefully, something awesome will come up with this :+1:

**Comment by bixuehujin** [comment]
You are saying “php-fpm will keep **objects** in memory for a number of requests before the child process is killed and restarted”, is there any article or document to support this?

Thanks

**Comment by nogrp** [comment]
I'll be more accurate with my comment - the execution model of `blink` is having a long-running process that never exits, so that execution model lets you have your objects effectively cached (correct term would be that the request never ended, so those objects never got garbage collected, ergo references to those object still exist). The **exact** same thing happens with `php-fpm` child process, which is why `php-fpm` is quick - it doesn't have to re-lex the files on every request, it doesn't have to re-establish database connections and it doesn't have to worry about memory allocation - if anything bad does happen, the child process will die, master process will receive the signal and it will simply boot a new child process (which is why `php-fpm` works only on operating systems that implement POSIX, and not on Windows). I don't have any documentation _yet_, I have _observed_ this behavior by going through fpm source code and analyzing it with valgrind. The way it deallocates memory is by killing the child process after some time or after a certain number of request it serves (accurate term would be that child tries to gracefully exit, but if it's killed or dies - it's irrelevant for the lifecycle). As I stated, this is what I observed through testing of several similar solutions (one of them is photon php framework, a Mongrel2 handler that exhibits unusually high performance). I don't have concrete proof, so you're correct in doubting what I'm writing here. Performance-wise - you could be achieving more performance - but you have another problem. Your HTTP parser is also PHP-based. FPM has to parse a fastcgi request which is much, much simpler and the piece of code doing that is written in C - there is no possible way you can be quicker under load than fpm is - which brings up another question - how resilient is your http parser, how does the stack behave under load etc. Hence, I would _probably_ not look at the performance you're offering but at other features. I know this is a lot of text, you are free to call bs on what I'm typing here, I actually prefer when I'm proven wrong, but as I said before - I don't want to take a dump on your project, I'm typing all of this with best intent - to provide accurate factual information. And the fact is - you can't provide more performance out of php than `fpm` can..

**Comment by bixuehujin** [comment]
One thing you may missed is that the http server of blink is provided by Swoole which implemented in C.

Anyway, thanks for your detail reply, and i will check on Mongrel2 and photon.
