### ISSUE TITLE
在TestCase的setUp里开启事务，tearDown()里回滚，但是通过actor()测试时事务没有生效

### ISSUE THREAD

**Issue by nbzx** [bixuehujin/blink#56]

**Comment by bixuehujin** [comment]
目前默认每个 actor 都创建了一个新的 `Application` 对象，新的 `Application` 也对应新的数据库链接，所以事务并没有生效。

如果想要事务生效，可以尝试重写 [这个](https://github.com/bixuehujin/blink-seed/blob/master/tests/TestCase.php#L10) 方法，让它返回一个单例的 `Application`。

**Comment by nbzx** [comment]
重载TestCase的actor方法如下代码，有啥副作用吗？
`return new RequestActor($this, $this->app);`

**Comment by bixuehujin** [comment]
应该也没啥问题。
