### ISSUE TITLE
单元测试$this->actor()->post传递body array时，控制器里使用$request->payload有报错

### ISSUE THREAD

**Issue by nbzx** [bixuehujin/blink#57]
报错内容
`blink\core\NotSupportedException: The content type: '' does not supported in vendor/blink/blink/src/http/Request.php:341`

原因猜测可能是RequestActor的doRequest方法里，用
`$this->request->{$key} = $value;`的方式，无法通过request->body赋值给reuqest->payload

**Comment by bixuehujin** [comment]
没有传 content-type 的原因，测试里面可以这样:

```
$this->actor()
  ->withJson()
```

**Comment by nbzx** [comment]
原来如此，学习了
