### ISSUE TITLE
using PSR-1

### ISSUE THREAD

**Issue by Whyounes** [bixuehujin/blink#8]
The framework should follow [PSR-1](http://www.php-fig.org/psr/psr-1/#3-namespace-and-class-names) for naming namespaces.

**Comment by bixuehujin** [comment]
Actually, PSR-1 doesn't dictate how namespaces should be named.

 Blink follows the Yii's convention for namespace and class naming. There is also a debate on how namespace should be named for Yii framework:

http://www.yiiframework.com/forum/index.php/topic/41622-namespaces-naming-convention/

**Comment by Whyounes** [comment]
I have the same arguments as the person the link you shared, so nothing to add here :smile:
