### ISSUE TITLE
Console commands not loaded

### ISSUE THREAD

**Issue by Whyounes** [bixuehujin/blink#9]
The doc says that commands should be inside the `src/commands` folder. Does that mean they are automatically loaded?

**Comment by bixuehujin** [comment]
No, You need configure the extra commands in `config/app.php` like the following:

``` php
'commands' => [
   'path/to/MyCommand1',
   'path/to/MyCommand2',
],
```

**Comment by Whyounes** [comment]
Thanks, there should be a commented section there!
[Suggestion]
Why not autoload it inside the `composer.json` file?
